import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { generateMariAIResponse } from '../lib/mariAI';
import { analytics } from '../lib/analytics';
import SEO from '../components/common/SEO';
import {
  TrendingUp,
  Sparkles,
  ShieldCheck,
  Share2,
  Zap,
  Globe,
  Bot,
  ArrowRight,
  Send,
  CheckCircle2,
  Activity,
  Layers,
  BarChart3
} from 'lucide-react';

const RalionGrowthIntelligenceProduct = () => {
  const [strategyPrompt, setStrategyPrompt] = useState('');
  const [aiStrategy, setAiStrategy] = useState('');
  const [loadingStrategy, setLoadingStrategy] = useState(false);

  const handleGenerateStrategy = async (e) => {
    e.preventDefault();
    if (!strategyPrompt.trim()) return;
    setLoadingStrategy(true);
    analytics.trackProductEvent('mari_ai_growth_demo', { prompt: strategyPrompt });
    const res = await generateMariAIResponse(
      `Develop an enterprise AI growth strategy and creative campaign plan for: ${strategyPrompt}`,
      'meta-llama/Llama-3.3-70B-Instruct-Turbo',
      'You are Mari AI — Your AI Business Growth Partner inside Ralion OS. Formulate a commercial growth brief, FLUX poster directions, CogVideoX reel concepts, and multi-channel publishing schedule.'
    );
    setAiStrategy(res);
    setLoadingStrategy(false);
  };

  return (
    <div className="min-h-screen bg-[#181818] text-white pt-32 pb-24 px-6 lg:px-12">
      <SEO
        title="Growth Studio & Social Intelligence | Ralion OS"
        description="Autonomous AI creative studio (FLUX, CogVideoX), multi-channel social publishing, and closed-loop performance analytics."
        canonical="https://rasalilabs.com/products/ralion-growth-intelligence"
      />

      <div className="max-w-7xl mx-auto">
        {/* Hero Section */}
        <div className="text-center max-w-4xl mx-auto mb-20">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/25 text-emerald-400 text-xs font-semibold uppercase tracking-wider mb-4">
            <TrendingUp size={14} /> Growth Studio & Social Intelligence
          </div>
          <h1 className="text-4xl md:text-6xl font-extrabold mb-4 tracking-tight bg-gradient-to-r from-white via-white/95 to-white/70 bg-clip-text text-transparent">
            Autonomous Creative Studio & Social Intelligence
          </h1>
          <p className="text-brand-gold font-bold text-xl md:text-2xl mb-6">
            Empowered to Prosper — Turn your brand into a self-optimizing revenue engine.
          </p>
          <p className="text-white/70 text-base md:text-lg max-w-3xl mx-auto leading-relaxed mb-10">
            Generate studio-grade commercial posters with FLUX, render 6-second marketing video reels with CogVideoX, compose and schedule across Facebook, Instagram, LinkedIn, and X, and measure real closed-loop revenue growth.
          </p>

          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link
              to="/ralion/register"
              className="px-8 py-4 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-600 text-black font-bold text-sm hover:scale-105 transition-all shadow-xl shadow-emerald-500/25 flex items-center gap-2"
            >
              Start Growth Studio <ArrowRight size={16} />
            </Link>
            <Link
              to="/request-demo"
              className="px-8 py-4 rounded-xl bg-white/10 hover:bg-white/15 text-white font-bold text-sm transition-all border border-white/15"
            >
              Book an Enterprise Demo
            </Link>
          </div>
        </div>

        {/* Interactive Mari AI Sandbox */}
        <div className="bg-[#1f1f1f] border border-emerald-500/30 rounded-3xl p-8 mb-20 shadow-2xl">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center">
              <Sparkles size={20} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-white">Interactive Growth Brief Generator</h3>
              <p className="text-white/50 text-xs">Simulate a campaign strategy brief generated by Mari AI.</p>
            </div>
          </div>

          <form onSubmit={handleGenerateStrategy} className="space-y-4 mb-6">
            <div className="flex flex-col sm:flex-row gap-3">
              <input
                type="text"
                placeholder="e.g. Launch a premium funeral cover campaign targeting corporate families in Botswana..."
                value={strategyPrompt}
                onChange={(e) => setStrategyPrompt(e.target.value)}
                className="flex-1 bg-black/50 border border-white/10 rounded-xl px-4 py-3 text-white text-xs focus:outline-none focus:border-emerald-400"
              />
              <button
                type="submit"
                disabled={loadingStrategy}
                className="px-6 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-black font-bold text-xs flex items-center justify-center gap-2 shrink-0 transition-colors"
              >
                {loadingStrategy ? 'Generating Strategy...' : 'Generate Brief'} <Send size={14} />
              </button>
            </div>
          </form>

          {aiStrategy && (
            <div className="p-6 rounded-2xl bg-black/60 border border-emerald-500/20 text-xs text-white/90 leading-relaxed whitespace-pre-wrap">
              <div className="text-brand-gold font-bold mb-2">Mari AI Strategic Blueprint:</div>
              {aiStrategy}
            </div>
          )}
        </div>

        {/* 4 Core Pillars of Growth Studio */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-20">
          <div className="bg-[#1f1f1f] border border-white/10 rounded-3xl p-6 hover:border-emerald-500/40 transition-all">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center mb-4">
              <Sparkles size={20} />
            </div>
            <h4 className="text-lg font-bold text-white mb-2">FLUX Poster Studio</h4>
            <p className="text-white/60 text-xs leading-relaxed">
              Generate commercial high-resolution advertising graphics and banners tailored to your product catalog.
            </p>
          </div>

          <div className="bg-[#1f1f1f] border border-white/10 rounded-3xl p-6 hover:border-brand-gold/40 transition-all">
            <div className="w-10 h-10 rounded-xl bg-brand-gold/10 text-brand-gold flex items-center justify-center mb-4">
              <Activity size={20} />
            </div>
            <h4 className="text-lg font-bold text-white mb-2">CogVideoX Video Reels</h4>
            <p className="text-white/60 text-xs leading-relaxed">
              Render dynamic 6-second video reels for social channels without expensive production overhead.
            </p>
          </div>

          <div className="bg-[#1f1f1f] border border-white/10 rounded-3xl p-6 hover:border-purple-500/40 transition-all">
            <div className="w-10 h-10 rounded-xl bg-purple-500/10 text-purple-400 flex items-center justify-center mb-4">
              <Share2 size={20} />
            </div>
            <h4 className="text-lg font-bold text-white mb-2">Multi-Channel Publish</h4>
            <p className="text-white/60 text-xs leading-relaxed">
              Connect social accounts to compose, schedule, and publish content queues from a single unified hub.
            </p>
          </div>

          <div className="bg-[#1f1f1f] border border-white/10 rounded-3xl p-6 hover:border-blue-500/40 transition-all">
            <div className="w-10 h-10 rounded-xl bg-blue-500/10 text-blue-400 flex items-center justify-center mb-4">
              <BarChart3 size={20} />
            </div>
            <h4 className="text-lg font-bold text-white mb-2">Closed-Loop Learning</h4>
            <p className="text-white/60 text-xs leading-relaxed">
              Real-time impressions, engagement, and conversion telemetry directly instruct Mari AI's next recommendations.
            </p>
          </div>
        </div>

        {/* Enterprise Bottom Banner */}
        <div className="bg-[#141414] border border-white/10 rounded-3xl p-8 flex flex-col md:flex-row items-center justify-between gap-6 text-xs text-white/70">
          <div className="flex items-center gap-4">
            <ShieldCheck size={32} className="text-emerald-400 shrink-0" />
            <div>
              <h4 className="text-white font-bold text-sm mb-0.5">Secure Social Connection Architecture</h4>
              <p>Social authentication tokens are encrypted at rest with server-side secret isolation. Zero third-party data leaks.</p>
            </div>
          </div>
          <Link
            to="/ralion/register"
            className="py-3 px-6 rounded-xl bg-emerald-500 text-black font-bold text-xs hover:scale-105 transition-transform shrink-0"
          >
            Launch Growth Studio
          </Link>
        </div>
      </div>
    </div>
  );
};

export default RalionGrowthIntelligenceProduct;
