import dotenv from 'dotenv';
dotenv.config({ path: 'apps/ralion/.env.local' });
import { metaAdapter } from '../apps/ralion/src/lib/services/social.service';

async function diagnoseMetaApp() {
  console.log('=== META APP & OAUTH URL PRE-REDIRECT TRACE ===\n');

  const appId = process.env.FACEBOOK_APP_ID || '1759273775121373';
  const appSecret = process.env.FACEBOOK_APP_SECRET || '44402f5d49f3be40102e2f11039499fe';
  const appToken = `${appId}|${appSecret}`;

  // 1. Check Meta App metadata & mode via App Access Token
  console.log('--- 1. Querying Meta App Details via Graph API ---');
  try {
    const res = await fetch(`https://graph.facebook.com/v19.0/${appId}?fields=id,name,category,app_type,live_mode,restrictions,business,contact_email&access_token=${encodeURIComponent(appToken)}`);
    const appData = await res.json();
    console.log('App Details:', JSON.stringify(appData, null, 2));
  } catch (e: any) {
    console.error('Failed to query App Details:', e.message);
  }

  // 2. Query App Roles (Admins, Developers, Testers)
  console.log('\n--- 2. Querying App Roles (Admins / Developers / Testers) ---');
  try {
    const rolesRes = await fetch(`https://graph.facebook.com/v19.0/${appId}/roles?access_token=${encodeURIComponent(appToken)}`);
    const rolesData = await rolesRes.json();
    console.log('App Roles:', JSON.stringify(rolesData, null, 2));
  } catch (e: any) {
    console.error('Failed to query App Roles:', e.message);
  }

  // 3. Query App Permissions & Features (Review status)
  console.log('\n--- 3. Querying App Permissions & Review Status ---');
  try {
    const permRes = await fetch(`https://graph.facebook.com/v19.0/${appId}/permissions?access_token=${encodeURIComponent(appToken)}`);
    const permData = await permRes.json();
    console.log('App Permissions:', JSON.stringify(permData, null, 2));
  } catch (e: any) {
    console.error('Failed to query App Permissions:', e.message);
  }

  // 4. Trace the exact OAuth URL generated by metaAdapter for various intents & scope configurations
  console.log('\n--- 4. Tracing Pre-Redirect OAuth URLs ---');
  const dummyState = 'test_signed_state_token_12345';

  // URL 1: Page connection (default Growth Studio)
  const urlPageConn = metaAdapter.getAuthUrl(dummyState, 'facebook', 'page_connection');
  console.log('\n[OAuth URL - Page Connection (Growth Studio)]');
  console.log(urlPageConn);

  // Parse parameters of URL 1
  const parsed1 = new URL(urlPageConn);
  console.log('Parsed Parameters (Page Connection):');
  console.log('  client_id:', parsed1.searchParams.get('client_id'));
  console.log('  redirect_uri:', parsed1.searchParams.get('redirect_uri'));
  console.log('  scope:', parsed1.searchParams.get('scope'));
  console.log('  response_type:', parsed1.searchParams.get('response_type'));
  console.log('  auth_type:', parsed1.searchParams.get('auth_type'));

  // URL 2: Basic Login (intent=login)
  const urlLogin = metaAdapter.getAuthUrl(dummyState, 'facebook', 'login');
  console.log('\n[OAuth URL - Basic Login (intent=login)]');
  console.log(urlLogin);

  const parsed2 = new URL(urlLogin);
  console.log('Parsed Parameters (Basic Login):');
  console.log('  client_id:', parsed2.searchParams.get('client_id'));
  console.log('  redirect_uri:', parsed2.searchParams.get('redirect_uri'));
  console.log('  scope:', parsed2.searchParams.get('scope'));
  console.log('  response_type:', parsed2.searchParams.get('response_type'));
  console.log('  auth_type:', parsed2.searchParams.get('auth_type'));

  // URL 3: Explicit Minimal Scopes (public_profile,email)
  const p3 = new URLSearchParams({
    client_id: appId,
    redirect_uri: metaAdapter.redirectUri('facebook'),
    state: dummyState,
    scope: 'public_profile,email',
    response_type: 'code',
    auth_type: 'rerequest',
  });
  console.log('\n[OAuth URL - Stage 1 (public_profile,email)]');
  console.log(`https://www.facebook.com/v19.0/dialog/oauth?${p3}`);

  // URL 4: Scope Set with pages_show_list (public_profile,email,pages_show_list)
  const p4 = new URLSearchParams({
    client_id: appId,
    redirect_uri: metaAdapter.redirectUri('facebook'),
    state: dummyState,
    scope: 'public_profile,email,pages_show_list',
    response_type: 'code',
    auth_type: 'rerequest',
  });
  console.log('\n[OAuth URL - Stage 2 (public_profile,email,pages_show_list)]');
  console.log(`https://www.facebook.com/v19.0/dialog/oauth?${p4}`);
}

diagnoseMetaApp().catch(console.error);
